-- Idempotent schema initialization
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- users
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin','editor')),
  created_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- texts
CREATE TABLE IF NOT EXISTS texts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  page TEXT NOT NULL,
  key TEXT NOT NULL,
  lang TEXT NOT NULL,
  value TEXT NOT NULL,
  UNIQUE(page, key, lang)
);
CREATE INDEX IF NOT EXISTS idx_texts_page_lang ON texts(page, lang);

-- images
CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  path TEXT NOT NULL,
  original_path TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('logo','slider','background','favicon')),
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_images_type ON images(type);

-- seo
CREATE TABLE IF NOT EXISTS seo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  page TEXT NOT NULL,
  lang TEXT NOT NULL,
  title TEXT,
  description TEXT,
  keywords TEXT,
  UNIQUE(page, lang)
);

-- Dashboard translations
INSERT OR IGNORE INTO texts (page, key, lang, value) VALUES
-- English (default)
('dashboard', 'title', 'en', 'CMS Dashboard'),
('dashboard', 'welcome', 'en', 'Welcome, {email}!'),
('dashboard', 'logout', 'en', 'Logout'),
('dashboard', 'images', 'en', 'Images'),
('dashboard', 'languages', 'en', 'Languages'),
('dashboard', 'texts', 'en', 'Texts'),
('dashboard', 'users', 'en', 'Users'),
('dashboard', 'quick_actions', 'en', 'Quick Actions'),
('dashboard', 'edit_texts', 'en', 'Edit Texts'),
('dashboard', 'content_management', 'en', 'Content management'),
('dashboard', 'upload_management', 'en', 'Upload and management'),
('dashboard', 'seo_settings', 'en', 'SEO Settings'),
('dashboard', 'meta_optimization', 'en', 'Meta tags and optimization'),
('dashboard', 'access_management', 'en', 'Access management'),

-- Russian
('dashboard', 'title', 'ru', 'Панель управления CMS'),
('dashboard', 'welcome', 'ru', 'Добро пожаловать, {email}!'),
('dashboard', 'logout', 'ru', 'Выйти'),
('dashboard', 'images', 'ru', 'Изображения'),
('dashboard', 'languages', 'ru', 'Языки'),
('dashboard', 'texts', 'ru', 'Тексты'),
('dashboard', 'users', 'ru', 'Пользователи'),
('dashboard', 'quick_actions', 'ru', 'Быстрые действия'),
('dashboard', 'edit_texts', 'ru', 'Редактировать тексты'),
('dashboard', 'content_management', 'ru', 'Управление контентом'),
('dashboard', 'upload_management', 'ru', 'Загрузка и управление'),
('dashboard', 'seo_settings', 'ru', 'SEO-настройки'),
('dashboard', 'meta_optimization', 'ru', 'Мета-теги и оптимизация'),
('dashboard', 'access_management', 'ru', 'Управление доступом'),

-- Ukrainian
('dashboard', 'title', 'ua', 'Панель керування CMS'),
('dashboard', 'welcome', 'ua', 'Ласкаво просимо, {email}!'),
('dashboard', 'logout', 'ua', 'Вийти'),
('dashboard', 'images', 'ua', 'Зображення'),
('dashboard', 'languages', 'ua', 'Мови'),
('dashboard', 'texts', 'ua', 'Тексти'),
('dashboard', 'users', 'ua', 'Користувачі'),
('dashboard', 'quick_actions', 'ua', 'Швидкі дії'),
('dashboard', 'edit_texts', 'ua', 'Редагувати тексти'),
('dashboard', 'content_management', 'ua', 'Управління контентом'),
('dashboard', 'upload_management', 'ua', 'Завантаження та управління'),
('dashboard', 'seo_settings', 'ua', 'SEO-налаштування'),
('dashboard', 'meta_optimization', 'ua', 'Мета-теги та оптимізація'),
('dashboard', 'access_management', 'ua', 'Управління доступом'),

-- CMS Texts Editor translations
('cms_texts', 'title', 'en', 'Text Editor'),
('cms_texts', 'subtitle', 'en', 'Content management'),
('cms_texts', 'back_to_dashboard', 'en', '← Back to Dashboard'),
('cms_texts', 'page', 'en', 'Page'),
('cms_texts', 'key', 'en', 'Key'),
('cms_texts', 'language', 'en', 'Language'),
('cms_texts', 'value', 'en', 'Value'),
('cms_texts', 'actions', 'en', 'Actions'),
('cms_texts', 'edit', 'en', 'Edit'),
('cms_texts', 'delete', 'en', 'Delete'),
('cms_texts', 'save', 'en', 'Save'),
('cms_texts', 'cancel', 'en', 'Cancel'),
('cms_texts', 'add_text', 'en', 'Add Text'),
('cms_texts', 'edit_text', 'en', 'Edit Text'),

('cms_texts', 'title', 'ru', 'Редактор текстов'),
('cms_texts', 'subtitle', 'ru', 'Управление контентом'),
('cms_texts', 'back_to_dashboard', 'ru', '← Назад к Dashboard'),
('cms_texts', 'page', 'ru', 'Страница'),
('cms_texts', 'key', 'ru', 'Ключ'),
('cms_texts', 'language', 'ru', 'Язык'),
('cms_texts', 'value', 'ru', 'Значение'),
('cms_texts', 'actions', 'ru', 'Действия'),
('cms_texts', 'edit', 'ru', 'Редактировать'),
('cms_texts', 'delete', 'ru', 'Удалить'),
('cms_texts', 'save', 'ru', 'Сохранить'),
('cms_texts', 'cancel', 'ru', 'Отмена'),
('cms_texts', 'add_text', 'ru', 'Добавить текст'),
('cms_texts', 'edit_text', 'ru', 'Редактировать текст'),

('cms_texts', 'title', 'ua', 'Редактор текстів'),
('cms_texts', 'subtitle', 'ua', 'Управління контентом'),
('cms_texts', 'back_to_dashboard', 'ua', '← Назад до Dashboard'),
('cms_texts', 'page', 'ua', 'Сторінка'),
('cms_texts', 'key', 'ua', 'Ключ'),
('cms_texts', 'language', 'ua', 'Мова'),
('cms_texts', 'value', 'ua', 'Значення'),
('cms_texts', 'actions', 'ua', 'Дії'),
('cms_texts', 'edit', 'ua', 'Редагувати'),
('cms_texts', 'delete', 'ua', 'Видалити'),
('cms_texts', 'save', 'ua', 'Зберегти'),
('cms_texts', 'cancel', 'ua', 'Скасувати'),
('cms_texts', 'add_text', 'ua', 'Додати текст'),
('cms_texts', 'edit_text', 'ua', 'Редагувати текст'),

-- Дополнительные переводы для CMS Texts Editor
('cms_texts', 'subtitle', 'en', 'Subtitle'),
('cms_texts', 'subtitle', 'ru', 'Подзаголовок'),
('cms_texts', 'subtitle', 'ua', 'Підзаголовок'),
('cms_texts', 'description', 'en', 'Description'),
('cms_texts', 'description', 'ru', 'Описание'),
('cms_texts', 'description', 'ua', 'Опис'),
('cms_texts', 'cta_text', 'en', 'CTA Button Text'),
('cms_texts', 'cta_text', 'ru', 'Текст кнопки CTA'),
('cms_texts', 'cta_text', 'ua', 'Текст кнопки CTA'),
('cms_texts', 'phone', 'en', 'Phone'),
('cms_texts', 'phone', 'ru', 'Телефон'),
('cms_texts', 'phone', 'ua', 'Телефон'),
('cms_texts', 'address', 'en', 'Address'),
('cms_texts', 'address', 'ru', 'Адрес'),
('cms_texts', 'address', 'ua', 'Адреса'),

-- Дополнительные переводы для страниц и языков
('cms_texts', 'home', 'en', 'Home'),
('cms_texts', 'home', 'ru', 'Главная'),
('cms_texts', 'home', 'ua', 'Головна'),
('cms_texts', 'about', 'en', 'About'),
('cms_texts', 'about', 'ru', 'О компании'),
('cms_texts', 'about', 'ua', 'Про компанію'),
('cms_texts', 'catalog', 'en', 'Catalog'),
('cms_texts', 'catalog', 'ru', 'Каталог'),
('cms_texts', 'catalog', 'ua', 'Каталог'),
('cms_texts', 'contacts', 'en', 'Contacts'),
('cms_texts', 'contacts', 'ru', 'Контакты'),
('cms_texts', 'contacts', 'ua', 'Контакти'),
('cms_texts', 'russian', 'en', 'Russian'),
('cms_texts', 'russian', 'ru', 'Русский'),
('cms_texts', 'russian', 'ua', 'Російська'),
('cms_texts', 'english', 'en', 'English'),
('cms_texts', 'english', 'ru', 'Английский'),
('cms_texts', 'english', 'ua', 'Англійська'),
('cms_texts', 'ukrainian', 'en', 'Ukrainian'),
('cms_texts', 'ukrainian', 'ru', 'Украинский'),
('cms_texts', 'ukrainian', 'ua', 'Українська'),

-- CMS Images Manager translations
('cms_images', 'title', 'en', 'Image Management'),
('cms_images', 'subtitle', 'en', 'Upload and optimize images'),
('cms_images', 'back_to_dashboard', 'en', '← Back to Dashboard'),
('cms_images', 'upload_image', 'en', 'Upload Image'),
('cms_images', 'image_type', 'en', 'Image Type'),
('cms_images', 'logo', 'en', 'Logo'),
('cms_images', 'slider', 'en', 'Slider'),
('cms_images', 'background', 'en', 'Background'),
('cms_images', 'favicon', 'en', 'Favicon'),
('cms_images', 'order', 'en', 'Order'),
('cms_images', 'upload', 'en', 'Upload'),
('cms_images', 'uploaded_images', 'en', 'Uploaded Images'),
('cms_images', 'name', 'en', 'Name'),
('cms_images', 'type', 'en', 'Type'),
('cms_images', 'size', 'en', 'Size'),
('cms_images', 'date', 'en', 'Date'),
('cms_images', 'actions', 'en', 'Actions'),
('cms_images', 'view', 'en', 'View'),
('cms_images', 'download', 'en', 'Download'),
('cms_images', 'delete', 'en', 'Delete'),

('cms_images', 'title', 'ru', 'Управление изображениями'),
('cms_images', 'subtitle', 'ru', 'Загрузка и оптимизация изображений'),
('cms_images', 'back_to_dashboard', 'ru', '← Назад к Dashboard'),
('cms_images', 'upload_image', 'ru', 'Загрузить изображение'),
('cms_images', 'image_type', 'ru', 'Тип изображения'),
('cms_images', 'logo', 'ru', 'Логотип'),
('cms_images', 'slider', 'ru', 'Слайдер'),
('cms_images', 'background', 'ru', 'Фон'),
('cms_images', 'favicon', 'ru', 'Иконка'),
('cms_images', 'order', 'ru', 'Порядок'),
('cms_images', 'upload', 'ru', 'Загрузить'),
('cms_images', 'uploaded_images', 'ru', 'Загруженные изображения'),
('cms_images', 'name', 'ru', 'Имя'),
('cms_images', 'type', 'ru', 'Тип'),
('cms_images', 'size', 'ru', 'Размер'),
('cms_images', 'date', 'ru', 'Дата'),
('cms_images', 'actions', 'ru', 'Действия'),
('cms_images', 'view', 'ru', 'Просмотр'),
('cms_images', 'download', 'ru', 'Скачать'),
('cms_images', 'delete', 'ru', 'Удалить'),

('cms_images', 'title', 'ua', 'Управління зображеннями'),
('cms_images', 'subtitle', 'ua', 'Завантаження та оптимізація зображень'),
('cms_images', 'back_to_dashboard', 'ua', '← Назад до Dashboard'),
('cms_images', 'upload_image', 'ua', 'Завантажити зображення'),
('cms_images', 'image_type', 'ua', 'Тип зображення'),
('cms_images', 'logo', 'ua', 'Логотип'),
('cms_images', 'slider', 'ua', 'Слайдер'),
('cms_images', 'background', 'ua', 'Фон'),
('cms_images', 'favicon', 'ua', 'Іконка'),
('cms_images', 'order', 'ua', 'Порядок'),
('cms_images', 'upload', 'ua', 'Завантажити'),
('cms_images', 'uploaded_images', 'ua', 'Завантажені зображення'),
('cms_images', 'name', 'ua', 'Ім''я'),

-- Дополнительные переводы для CMS Images Manager
('cms_images', 'upload_images', 'en', 'Upload Images'),
('cms_images', 'upload_images', 'ru', 'Загрузка изображений'),
('cms_images', 'upload_images', 'ua', 'Завантаження зображень'),
('cms_images', 'image_type', 'en', 'Image Type'),
('cms_images', 'image_type', 'ru', 'Тип изображения'),
('cms_images', 'image_type', 'ua', 'Тип зображення'),
('cms_images', 'select_type', 'en', 'Select Type'),
('cms_images', 'select_type', 'ru', 'Выберите тип'),
('cms_images', 'select_type', 'ua', 'Виберіть тип'),
('cms_images', 'logo', 'en', 'Logo'),
('cms_images', 'logo', 'ru', 'Логотип'),
('cms_images', 'logo', 'ua', 'Логотип'),
('cms_images', 'slider', 'en', 'Slider'),
('cms_images', 'slider', 'ru', 'Слайдер'),
('cms_images', 'slider', 'ua', 'Слайдер'),
('cms_images', 'background', 'en', 'Background'),
('cms_images', 'background', 'ru', 'Фон'),
('cms_images', 'background', 'ua', 'Фон'),
('cms_images', 'favicon', 'en', 'Favicon'),
('cms_images', 'favicon', 'ru', 'Favicon'),
('cms_images', 'favicon', 'ua', 'Favicon'),
('cms_images', 'image_file', 'en', 'Image File'),
('cms_images', 'image_file', 'ru', 'Файл изображения'),
('cms_images', 'image_file', 'ua', 'Файл зображення'),
('cms_images', 'upload', 'en', 'Upload'),
('cms_images', 'upload', 'ru', 'Загрузить'),
('cms_images', 'upload', 'ua', 'Завантажити'),
('cms_images', 'uploading', 'en', 'Uploading...'),
('cms_images', 'uploading', 'ru', 'Загрузка...'),
('cms_images', 'uploading', 'ua', 'Завантаження...'),
('cms_images', 'no_images', 'en', 'No Images'),
('cms_images', 'no_images', 'ru', 'Нет изображений'),
('cms_images', 'no_images', 'ua', 'Немає зображень'),
('cms_images', 'drag_to_reorder', 'en', 'Drag to reorder'),
('cms_images', 'drag_to_reorder', 'ru', 'Перетащите изображения для изменения порядка'),
('cms_images', 'drag_to_reorder', 'ua', 'Перетягніть зображення для зміни порядку'),
('cms_images', 'unknown', 'en', 'Unknown'),
('cms_images', 'unknown', 'ru', 'Неизвестно'),
('cms_images', 'unknown', 'ua', 'Невідомо'),
('cms_images', 'order', 'en', 'Order'),
('cms_images', 'order', 'ru', 'Порядок'),
('cms_images', 'order', 'ua', 'Порядок'),
('cms_images', 'file_too_large', 'en', 'File too large. Max size: 2MB'),
('cms_images', 'file_too_large', 'ru', 'Файл слишком большой. Максимальный размер: 2MB'),
('cms_images', 'file_too_large', 'ua', 'Файл занадто великий. Максимальний розмір: 2MB'),
('cms_images', 'unsupported_format', 'en', 'Unsupported file format. Allowed: JPG, PNG, WebP, ICO'),
('cms_images', 'unsupported_format', 'ru', 'Неподдерживаемый формат файла. Разрешены: JPG, PNG, WebP, ICO'),
('cms_images', 'unsupported_format', 'ua', 'Непідтримуваний формат файлу. Дозволені: JPG, PNG, WebP, ICO'),
('cms_images', 'load_error', 'en', 'Load error'),
('cms_images', 'load_error', 'ru', 'Ошибка загрузки'),
('cms_images', 'load_error', 'ua', 'Помилка завантаження'),
('cms_images', 'select_file_and_type', 'en', 'Please select file and image type'),
('cms_images', 'select_file_and_type', 'ru', 'Пожалуйста, выберите файл и тип изображения'),
('cms_images', 'select_file_and_type', 'ua', 'Будь ласка, виберіть файл та тип зображення'),
('cms_images', 'upload_success', 'en', 'Image uploaded successfully'),
('cms_images', 'upload_success', 'ru', 'Изображение успешно загружено'),
('cms_images', 'upload_success', 'ua', 'Зображення успішно завантажено'),
('cms_images', 'upload_error', 'en', 'Upload error'),
('cms_images', 'upload_error', 'ru', 'Ошибка загрузки'),
('cms_images', 'upload_error', 'ua', 'Помилка завантаження'),
('cms_images', 'confirm_delete', 'en', 'Are you sure you want to delete this image?'),
('cms_images', 'confirm_delete', 'ru', 'Вы уверены, что хотите удалить это изображение?'),
('cms_images', 'confirm_delete', 'ua', 'Ви впевнені, що хочете видалити це зображення?'),
('cms_images', 'delete_success', 'en', 'Image deleted successfully'),
('cms_images', 'delete_success', 'ru', 'Изображение удалено'),
('cms_images', 'delete_success', 'ua', 'Зображення видалено'),
('cms_images', 'delete_error', 'en', 'Delete error'),
('cms_images', 'delete_error', 'ru', 'Ошибка удаления'),
('cms_images', 'delete_error', 'ua', 'Помилка видалення'),
('cms_images', 'close', 'en', 'Close'),
('cms_images', 'close', 'ru', 'Закрыть'),
('cms_images', 'close', 'ua', 'Закрити'),
('cms_images', 'type', 'ua', 'Тип'),
('cms_images', 'size', 'ua', 'Розмір'),
('cms_images', 'date', 'ua', 'Дата'),
('cms_images', 'actions', 'ua', 'Дії'),
('cms_images', 'view', 'ua', 'Перегляд'),
('cms_images', 'download', 'ua', 'Завантажити'),
('cms_images', 'delete', 'ua', 'Видалити'),

-- CMS SEO Manager translations
('cms_seo', 'title', 'en', 'SEO Settings'),
('cms_seo', 'subtitle', 'en', 'Meta tags and search engine optimization'),
('cms_seo', 'back_to_dashboard', 'en', '← Back to Dashboard'),
('cms_seo', 'page', 'en', 'Page'),
('cms_seo', 'language', 'en', 'Language'),
('cms_seo', 'title_tag', 'en', 'Title'),
('cms_seo', 'description', 'en', 'Description'),
('cms_seo', 'keywords', 'en', 'Keywords'),
('cms_seo', 'save', 'en', 'Save'),
('cms_seo', 'cancel', 'en', 'Cancel'),
('cms_seo', 'add_seo', 'en', 'Add SEO'),
('cms_seo', 'edit_seo', 'en', 'Edit SEO'),

('cms_seo', 'title', 'ru', 'SEO-настройки'),
('cms_seo', 'subtitle', 'ru', 'Мета-теги и оптимизация для поисковых систем'),
('cms_seo', 'back_to_dashboard', 'ru', '← Назад к Dashboard'),
('cms_seo', 'page', 'ru', 'Страница'),
('cms_seo', 'language', 'ru', 'Язык'),
('cms_seo', 'title_tag', 'ru', 'Заголовок'),
('cms_seo', 'description', 'ru', 'Описание'),
('cms_seo', 'keywords', 'ru', 'Ключевые слова'),
('cms_seo', 'save', 'ru', 'Сохранить'),
('cms_seo', 'cancel', 'ru', 'Отмена'),
('cms_seo', 'add_seo', 'ru', 'Добавить SEO'),
('cms_seo', 'edit_seo', 'ru', 'Редактировать SEO'),

('cms_seo', 'title', 'ua', 'SEO-налаштування'),
('cms_seo', 'subtitle', 'ua', 'Мета-теги та оптимізація для пошукових систем'),
('cms_seo', 'back_to_dashboard', 'ua', '← Назад до Dashboard'),
('cms_seo', 'page', 'ua', 'Сторінка'),
('cms_seo', 'language', 'ua', 'Мова'),
('cms_seo', 'title_tag', 'ua', 'Заголовок'),
('cms_seo', 'description', 'ua', 'Опис'),
('cms_seo', 'keywords', 'ua', 'Ключові слова'),
('cms_seo', 'save', 'ua', 'Зберегти'),
('cms_seo', 'cancel', 'ua', 'Скасувати'),
('cms_seo', 'add_seo', 'ua', 'Додати SEO'),
('cms_seo', 'edit_seo', 'ua', 'Редагувати SEO'),

-- Дополнительные переводы для CMS SEO Manager
('cms_seo', 'seo_settings', 'en', 'SEO Settings'),
('cms_seo', 'seo_settings', 'ru', 'Настройки SEO'),
('cms_seo', 'seo_settings', 'ua', 'Налаштування SEO'),
('cms_seo', 'home', 'en', 'Home'),
('cms_seo', 'home', 'ru', 'Главная'),
('cms_seo', 'home', 'ua', 'Головна'),
('cms_seo', 'about', 'en', 'About'),
('cms_seo', 'about', 'ru', 'О компании'),
('cms_seo', 'about', 'ua', 'Про компанію'),
('cms_seo', 'catalog', 'en', 'Catalog'),
('cms_seo', 'catalog', 'ru', 'Каталог'),
('cms_seo', 'catalog', 'ua', 'Каталог'),
('cms_seo', 'contacts', 'en', 'Contacts'),
('cms_seo', 'contacts', 'ru', 'Контакты'),
('cms_seo', 'contacts', 'ua', 'Контакти'),
('cms_seo', 'russian', 'en', 'Russian'),
('cms_seo', 'russian', 'ru', 'Русский'),
('cms_seo', 'russian', 'ua', 'Російська'),
('cms_seo', 'english', 'en', 'English'),
('cms_seo', 'english', 'ru', 'Английский'),
('cms_seo', 'english', 'ua', 'Англійська'),
('cms_seo', 'ukrainian', 'en', 'Ukrainian'),
('cms_seo', 'ukrainian', 'ru', 'Украинский'),
('cms_seo', 'ukrainian', 'ua', 'Українська'),
('cms_seo', 'title_placeholder', 'en', 'Page title (up to 60 characters)'),
('cms_seo', 'title_placeholder', 'ru', 'Заголовок страницы (до 60 символов)'),
('cms_seo', 'title_placeholder', 'ua', 'Заголовок сторінки (до 60 символів)'),
('cms_seo', 'description_placeholder', 'en', 'Page description (up to 160 characters)'),
('cms_seo', 'description_placeholder', 'ru', 'Описание страницы (до 160 символов)'),
('cms_seo', 'description_placeholder', 'ua', 'Опис сторінки (до 160 символів)'),
('cms_seo', 'keywords_placeholder', 'en', 'Keywords separated by commas (up to 255 characters)'),
('cms_seo', 'keywords_placeholder', 'ru', 'Ключевые слова через запятую (до 255 символов)'),
('cms_seo', 'keywords_placeholder', 'ua', 'Ключові слова через кому (до 255 символів)'),
('cms_seo', 'characters', 'en', 'characters'),
('cms_seo', 'characters', 'ru', 'символов'),
('cms_seo', 'characters', 'ua', 'символів'),
('cms_seo', 'saving', 'en', 'Saving...'),
('cms_seo', 'saving', 'ru', 'Сохранение...'),
('cms_seo', 'saving', 'ua', 'Збереження...'),
('cms_seo', 'preview', 'en', 'Preview'),
('cms_seo', 'preview', 'ru', 'Предпросмотр'),
('cms_seo', 'preview', 'ua', 'Попередній перегляд'),
('cms_seo', 'google_preview', 'en', 'How it will look in Google:'),
('cms_seo', 'google_preview', 'ru', 'Как будет выглядеть в Google:'),
('cms_seo', 'google_preview', 'ua', 'Як буде виглядати в Google:'),
('cms_seo', 'enter_title', 'en', 'Enter title'),
('cms_seo', 'enter_title', 'ru', 'Введите заголовок'),
('cms_seo', 'enter_title', 'ua', 'Введіть заголовок'),
('cms_seo', 'enter_description', 'en', 'Enter description'),
('cms_seo', 'enter_description', 'ru', 'Введите описание'),
('cms_seo', 'enter_description', 'ua', 'Введіть опис'),
('cms_seo', 'enter_keywords', 'en', 'Enter keywords'),
('cms_seo', 'enter_keywords', 'ru', 'Введите ключевые слова'),
('cms_seo', 'enter_keywords', 'ua', 'Введіть ключові слова'),
('cms_seo', 'html_code', 'en', 'HTML code:'),
('cms_seo', 'html_code', 'ru', 'HTML код:'),
('cms_seo', 'html_code', 'ua', 'HTML код:'),
('cms_seo', 'load_error', 'en', 'Load error'),
('cms_seo', 'load_error', 'ru', 'Ошибка загрузки'),
('cms_seo', 'load_error', 'ua', 'Помилка завантаження'),
('cms_seo', 'save_success', 'en', 'SEO data saved successfully'),
('cms_seo', 'save_success', 'ru', 'SEO данные успешно сохранены'),
('cms_seo', 'save_success', 'ua', 'SEO дані успішно збережено'),
('cms_seo', 'save_error', 'en', 'Save error'),
('cms_seo', 'save_error', 'ru', 'Ошибка сохранения'),
('cms_seo', 'save_error', 'ua', 'Помилка збереження'),

-- CMS Users Manager translations
('cms_users', 'title', 'en', 'User Management'),
('cms_users', 'title', 'ru', 'Управление пользователями'),
('cms_users', 'title', 'ua', 'Управління користувачами'),
('cms_users', 'subtitle', 'en', 'Add and manage system users'),
('cms_users', 'subtitle', 'ru', 'Добавление и управление пользователями системы'),
('cms_users', 'subtitle', 'ua', 'Додавання та управління користувачами системи'),
('cms_users', 'back_to_dashboard', 'en', '← Back to Dashboard'),
('cms_users', 'back_to_dashboard', 'ru', '← Назад к Dashboard'),
('cms_users', 'back_to_dashboard', 'ua', '← Назад до Dashboard'),
('cms_users', 'add_user', 'en', 'Add User'),
('cms_users', 'add_user', 'ru', 'Добавить пользователя'),
('cms_users', 'add_user', 'ua', 'Додати користувача'),
('cms_users', 'system_users', 'en', 'System Users'),
('cms_users', 'system_users', 'ru', 'Пользователи системы'),
('cms_users', 'system_users', 'ua', 'Користувачі системи'),
('cms_users', 'email', 'en', 'Email'),
('cms_users', 'email', 'ru', 'Email'),
('cms_users', 'email', 'ua', 'Email'),
('cms_users', 'role', 'en', 'Role'),
('cms_users', 'role', 'ru', 'Роль'),
('cms_users', 'role', 'ua', 'Роль'),
('cms_users', 'created_date', 'en', 'Created Date'),
('cms_users', 'created_date', 'ru', 'Дата создания'),
('cms_users', 'created_date', 'ua', 'Дата створення'),
('cms_users', 'actions', 'en', 'Actions'),
('cms_users', 'actions', 'ru', 'Действия'),
('cms_users', 'actions', 'ua', 'Дії'),
('cms_users', 'password', 'en', 'Password'),
('cms_users', 'password', 'ru', 'Пароль'),
('cms_users', 'password', 'ua', 'Пароль'),
('cms_users', 'cancel', 'en', 'Cancel'),
('cms_users', 'cancel', 'ru', 'Отмена'),
('cms_users', 'cancel', 'ua', 'Скасувати'),
('cms_users', 'create', 'en', 'Create'),
('cms_users', 'create', 'ru', 'Создать'),
('cms_users', 'create', 'ua', 'Створити'),
('cms_users', 'reset_password', 'en', 'Reset Password'),
('cms_users', 'reset_password', 'ru', 'Сбросить пароль'),
('cms_users', 'reset_password', 'ua', 'Скинути пароль'),
('cms_users', 'new_password', 'en', 'New Password'),
('cms_users', 'new_password', 'ru', 'Новый пароль'),
('cms_users', 'new_password', 'ua', 'Новий пароль'),
('cms_users', 'reset', 'en', 'Reset'),
('cms_users', 'reset', 'ru', 'Сбросить'),
('cms_users', 'reset', 'ua', 'Скинути'),
('cms_users', 'user_created', 'en', 'User created successfully'),
('cms_users', 'user_created', 'ru', 'Пользователь успешно создан'),
('cms_users', 'user_created', 'ua', 'Користувача успішно створено'),
('cms_users', 'create_error', 'en', 'Error creating user'),
('cms_users', 'create_error', 'ru', 'Ошибка создания пользователя'),
('cms_users', 'create_error', 'ua', 'Помилка створення користувача'),
('cms_users', 'password_reset', 'en', 'Password reset successfully'),
('cms_users', 'password_reset', 'ru', 'Пароль успешно сброшен'),
('cms_users', 'password_reset', 'ua', 'Пароль успішно скинуто'),
('cms_users', 'reset_error', 'en', 'Error resetting password'),
('cms_users', 'reset_error', 'ru', 'Ошибка сброса пароля'),
('cms_users', 'reset_error', 'ua', 'Помилка скидання пароля'),
('cms_users', 'load_error', 'en', 'Error loading users'),
('cms_users', 'load_error', 'ru', 'Ошибка загрузки пользователей'),
('cms_users', 'load_error', 'ua', 'Помилка завантаження користувачів'),
('cms_users', 'no_users', 'en', 'No users found'),
('cms_users', 'no_users', 'ru', 'Пользователи не найдены'),
('cms_users', 'no_users', 'ua', 'Користувачі не знайдені'),
('cms_users', 'delete', 'en', 'Delete'),
('cms_users', 'delete', 'ru', 'Удалить'),
('cms_users', 'delete', 'ua', 'Видалити'),
('cms_users', 'confirm_delete', 'en', 'Are you sure you want to delete this user?'),
('cms_users', 'confirm_delete', 'ru', 'Вы уверены, что хотите удалить этого пользователя?'),
('cms_users', 'confirm_delete', 'ua', 'Ви впевнені, що хочете видалити цього користувача?'),
('cms_users', 'user_deleted', 'en', 'User deleted successfully'),
('cms_users', 'user_deleted', 'ru', 'Пользователь успешно удален'),
('cms_users', 'user_deleted', 'ua', 'Користувача успішно видалено'),
('cms_users', 'delete_error', 'en', 'Error deleting user'),
('cms_users', 'delete_error', 'ru', 'Ошибка удаления пользователя'),
('cms_users', 'delete_error', 'ua', 'Помилка видалення користувача');


